name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        curl -Lo terraform.zip https://releases.hashicorp.com/terraform/$(curl -s https://releases.hashicorp.com/terraform/ | grep -oP 'terraform/\K[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -n 1)/terraform_$(curl -s https://releases.hashicorp.com/terraform/ | grep -oP 'terraform/\K[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -n 1)_linux_amd64.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform -install-autocomplete

    - name: Configure AWS Credentials
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = AKIARWPFIV23K7LPS2QO" >> ~/.aws/credentials
        echo "aws_secret_access_key = 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" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        echo "region = ap-south-1" >> ~/.aws/config

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --name my-eks-cluster-1 --region ap-south-1

    - name: Apply Kubernetes Manifests
      run: |
        sudo -i -u $USER bash <<EOF
        kubectl apply -f $(pwd)/
        EOF
